// Code generated by goctl. DO NOT EDIT.
package types

type UploadFileRequest struct {
}

type UploadFileResponse struct {
}

type DownloadFileRequest struct {
}

type DownloadFileResponse struct {
}
