// Code generated by goctl. DO NOT EDIT.
// Source: test.proto

package testservice

import (
	"context"

	"github.com/BingguWang/bingBar/service/testRpc/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SimpleReq  = pb.SimpleReq
	SimpleResp = pb.SimpleResp

	TestService interface {
		TestRpcFunc(ctx context.Context, in *SimpleReq, opts ...grpc.CallOption) (*SimpleResp, error)
	}

	defaultTestService struct {
		cli zrpc.Client
	}
)

func NewTestService(cli zrpc.Client) TestService {
	return &defaultTestService{
		cli: cli,
	}
}

func (m *defaultTestService) TestRpcFunc(ctx context.Context, in *SimpleReq, opts ...grpc.CallOption) (*SimpleResp, error) {
	client := pb.NewTestServiceClient(m.cli.Conn())
	return client.TestRpcFunc(ctx, in, opts...)
}
