// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	file "github.com/BingguWang/bingBar/service/file/api/internal/handler/file"
	"github.com/BingguWang/bingBar/service/file/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: file.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/download",
				Handler: file.DownloadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/filecenter/v1"),
	)
}
