// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
	Location string `json:"location"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type FollowReq struct {
	Uid int64 `json:"uid"`
}

type FollowResp struct {
	RetMsg string `json:"retMsg"`
}

type UnFollowReq struct {
	Uid int64 `json:"uid"`
}

type UnFollowResp struct {
	RetMsg string `json:"retMsg"`
}

type GetFollowListReq struct {
	PageNo   int64 `json:"pageNo"`
	PageSize int64 `json:"pageSize"`
}

type GetFollowListResp struct {
	RetMsg   string `json:"retMsg"`
	UserList []User `json:"userList"`
}

type GetFansListReq struct {
	PageNo   int64 `json:"pageNo"`
	PageSize int64 `json:"pageSize"`
}

type GetFansListResp struct {
	RetMsg   string `json:"retMsg"`
	UserList []User `json:"userList"`
}

type GetFriendListReq struct {
	PageNo   int64 `json:"pageNo"`
	PageSize int64 `json:"pageSize"`
}

type GetFriendListResp struct {
	RetMsg   string `json:"retMsg"`
	UserList []User `json:"userList"`
}

type GetMutualFollowListReq struct {
	Followed int64 `json:"followed"`
	PageSize int64 `json:"pageSize"`
}

type GetMutualFollowListResp struct {
	RetMsg   string `json:"retMsg"`
	UserList []User `json:"userList"`
	Total    int64  `json:"total"`
}

type GetMutualFriendListReq struct {
	Uid      int64 `json:"uid"`
	PageSize int64 `json:"pageSize"`
}

type GetMutualFriendListResp struct {
	RetMsg   string `json:"retMsg"`
	UserList []User `json:"userList"`
	Total    int64  `json:"total"`
}

type EditUserReq struct {
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
	Location string `json:"location"`
}

type EditUserResp struct {
	RetMsg string `json:"retMsg"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type FansHistoryReq struct {
	Start int64 `json:"start"`
	End   int64 `json:"end"`
}

type FansHistoryResp struct {
	HistoryItems []HistoryItem `json:"historyItem"`
}

type HistoryItem struct {
	Value  int64 `json:"value"`
	TimeAt int64 `json:"timeAt"`
}
